name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.0
    - name: Build
      working-directory: V2Speak
      run: msbuild V2Speak.csproj - p:Configuration=Release
    - name: Save
      uses: actions/upload-artifact@v1.0.0
      with: 
        name: main
        path: V2Speak\bin\Release\V2Speak.exe
